package gregtechfoodoption.recipe.chain;


public class MineralWaterChain {
    public static void init()
    {
/*        CANNER_RECIPES.recipeBuilder()
                .fluidInputs(Water.getFluid(1000))
                .inputs(DEWAR_FLASK.getStackForm())
                .outputs(MINERAL_WATER.getStackForm())
                .EUt(2)
                .duration(40)
                .buildAndRegister();
        ASSEMBLER_RECIPES.recipeBuilder()
                .inputs(DEWAR_FLASK_CASING.getStackForm(), DEWAR_FLASK_CAP.getStackForm())
                .outputs(DEWAR_FLASK.getStackForm())
                .EUt(4)
                .duration(40)
                .buildAndRegister();
        ASSEMBLER_RECIPES.recipeBuilder()
                .input(foil, Zylon, 2)
                .input(plateCurved, TungstenSteel, 2)
                .input(ring, TungstenSteel)
                .outputs(DEWAR_FLASK_CAP.getStackForm())
                .EUt(30720)
                .duration(100)
                .buildAndRegister();
        DISASSEMBLER_RECIPES.recipeBuilder()
                .inputs(USED_DEWAR_FLASK.getStackForm())
                .outputs(LEACHED_DEWAR_FLASK_CASING.getStackForm(), DEWAR_FLASK_CAP.getStackForm())
                .EUt(120)
                .duration(160)
                .buildAndRegister();
        ASSEMBLER_RECIPES.recipeBuilder()
                .inputs(GTFOMaterialHandler.PolymoscoviumPentahalide.getItemStack(), LEACHED_DEWAR_FLASK_CASING.getStackForm())
                .fluidInputs(Polytetrafluoroethylene.getFluid(96))
                .chancedOutput(DEWAR_FLASK_CASING.getStackForm(), 5000, 0)
                .EUt((V[GAValues.UXV]/16) * 15)
                .duration(1000)
                .buildAndRegister();
        ASSEMBLER_RECIPES.recipeBuilder()
                .inputs(GTFOMaterialHandler.NonToxicPolymoscoviumPentahalideCurvedSheet.getItemStack(2))
                .outputs(DEWAR_FLASK_CASING.getStackForm())
                .EUt(V[GAValues.UIV] * 15/16)
                .duration(400)
                .buildAndRegister();
        BENDER_RECIPES.recipeBuilder()
                .inputs(GTFOMaterialHandler.NonToxicPolymoscoviumPentahalideSheet.getItemStack())
                .circuitMeta(1)
                .outputs(GTFOMaterialHandler.NonToxicPolymoscoviumPentahalideCurvedSheet.getItemStack())
                .EUt(V[GAValues.UMV] * 15/16)
                .duration(874)
                .buildAndRegister();
        FORMING_PRESS_RECIPES.recipeBuilder()
                .input(plate, Polytetrafluoroethylene, 2)
                .inputs(GTFOMaterialHandler.PolymoscoviumPentahalideSheet.getItemStack())
                .EUt((V[GAValues.UXV]/16) * 15)
                .outputs(GTFOMaterialHandler.NonToxicPolymoscoviumPentahalideSheet.getItemStack())
                .duration(400)
                .buildAndRegister();
        STELLAR_FORGE_RECIPES.recipeBuilder()
                .inputs(GTFOMaterialHandler.PolymoscoviumPentahalide.getItemStack())
                .fluidInputs(Gluons.getFluid(50))
                .outputs(GTFOMaterialHandler.PolymoscoviumPentahalideSheet.getItemStack())
                .EUt(V[GAValues.UHV] * 15/16)
                .duration(300)
                .buildAndRegister();
        AUTOCLAVE_RECIPES.recipeBuilder()
                .inputs(COSMIC_MESH.getStackForm())
                .fluidInputs(GTFOMaterialHandler.HighlyPolymerizedMoscoviumPentahalides.getFluid(216))
                .outputs(GTFOMaterialHandler.PolymoscoviumPentahalide.getItemStack())
                .EUt(V[GAValues.UIV] * 15/16)
                .duration(1500)
                .buildAndRegister();
        EXTRACTOR_RECIPES.recipeBuilder()
                .inputs(GTFOMaterialHandler.OligoPolymerizedMoscoviumPentahalides.getItemStack())
                .fluidOutputs(GTFOMaterialHandler.HighlyPolymerizedMoscoviumPentahalides.getFluid(144))
                .EUt(V[GAValues.ZPM] * 15/16)
                .duration(300)
                .buildAndRegister();
        AUTOCLAVE_RECIPES.recipeBuilder()
                .inputs(GTFOMaterialHandler.WellMixedMoscoviumPentahalides.getItemStack())
                .fluidInputs(Helium.getFluid(1000))
                .outputs(GTFOMaterialHandler.OligoPolymerizedMoscoviumPentahalides.getItemStack())
                .EUt(V[GAValues.UEV] * 15/16)
                .duration(1100)
                .buildAndRegister();
        LARGE_MIXER_RECIPES.recipeBuilder()
                .inputs(GTFOMaterialHandler.MoscoviumPentafluoride.getItemStack(), GTFOMaterialHandler.MoscoviumPentachloride.getItemStack(), GTFOMaterialHandler.MoscoviumPentabromide.getItemStack(), GTFOMaterialHandler.MoscoviumPentaiodide.getItemStack(), GTFOMaterialHandler.MoscoviumPentaastatide.getItemStack(), GTFOMaterialHandler.MoscoviumPentatennesside.getItemStack())
                .outputs(GTFOMaterialHandler.WellMixedMoscoviumPentahalides.getItemStack(6))
                .EUt(1920)
                .duration(2100)
                .buildAndRegister();


        CHEMICAL_RECIPES.recipeBuilder()
                .inputs(GTFOMaterialHandler.MoscoviumTrifluoride.getItemStack(4))
                .fluidInputs(GTFOMaterialHandler.ChlorineTrifluoride.getFluid(1000))
                .outputs(GTFOMaterialHandler.MoscoviumPentafluoride.getItemStack(6))
                .fluidOutputs(GTFOMaterialHandler.ChlorineFluoride.getFluid(1000))
                .EUt(V[ZPM] * 15/16)
                .duration(178)
                .buildAndRegister();
        ELECTROLYZER_RECIPES.recipeBuilder()
                .fluidInputs(GTFOMaterialHandler.ChlorineFluoride.getFluid(1000))
                .fluidOutputs(Chlorine.getFluid(1000), Fluorine.getFluid(1000))
                .EUt(120)
                .duration(200)
                .buildAndRegister();
        CHEMICAL_RECIPES.recipeBuilder()
                .fluidInputs(Chlorine.getFluid(1000), Fluorine.getFluid(3000))
                .fluidOutputs(GTFOMaterialHandler.ChlorineTrifluoride.getFluid(1000))
                .EUt(1920)
                .duration(80)
                .buildAndRegister();
        CHEMICAL_RECIPES.recipeBuilder()
                .inputs(GTFOMaterialHandler.MoscoviumIiiOxide.getItemStack(5))
                .fluidInputs(HydrofluoricAcid.getFluid(6000))
                .outputs(GTFOMaterialHandler.MoscoviumTrifluoride.getItemStack(8))
                .fluidOutputs(Water.getFluid(3000))
                .EUt(7680)
                .duration(380)
                .buildAndRegister();
        BLAST_RECIPES.recipeBuilder()
                .input(dust, Moscovium, 2)
                .fluidInputs(Water.getFluid(3000))
                .blastFurnaceTemp(750)
                .outputs(GTFOMaterialHandler.MoscoviumIiiOxide.getItemStack(5))
                .fluidOutputs(Hydrogen.getFluid(6000))
                .EUt(V[UV] * 15/16)
                .duration(460)
                .buildAndRegister();

        LARGE_CHEMICAL_RECIPES.recipeBuilder()
                .input(dust, Sodium, 2)
                .inputs(GTFOMaterialHandler.TitaniumCarbide.getItemStack(6), GTFOMaterialHandler.MoscoviumHafniumOctadecachloride.getItemStack(31))
                .outputs(GTFOMaterialHandler.SaltyTitaniumDichlorideMixture.getItemStack(13), GTFOMaterialHandler.DecayedMoscovium.getItemStack(8), GTFOMaterialHandler.HighlyIrradiatedHafniumCarbide.getItemStack(3), GTFOMaterialHandler.MoscoviumPentachloride.getItemStack(12))
                .EUt(V[GAValues.UEV] * 15/16)
                .duration(860)
                .buildAndRegister();
        CENTRIFUGE_RECIPES.recipeBuilder()
                .inputs(GTFOMaterialHandler.HighlyIrradiatedHafniumCarbide.getItemStack(3))
                .outputs(HafniumCarbide.getItemStack())
                .output(dust, TungstenCarbide, 2)
                .EUt(7680)
                .duration(660)
                .buildAndRegister();
        CENTRIFUGE_RECIPES.recipeBuilder()
                .inputs(GTFOMaterialHandler.DecayedMoscovium.getItemStack(8))
                .output(dust, Moscovium, 6)
                .output(dust, Nihonium, 2)
                .EUt(7680)
                .duration(1020)
                .buildAndRegister();
        CENTRIFUGE_RECIPES.recipeBuilder()
                .inputs(GTFOMaterialHandler.SaltyTitaniumDichlorideMixture.getItemStack(13))
                .output(dust, Salt, 4)
                .outputs(GTFOMaterialHandler.TitaniumDichloride.getItemStack(9))
                .EUt(7680)
                .duration(150)
                .buildAndRegister();
        BLAST_RECIPES.recipeBuilder()
                .inputs(GTFOMaterialHandler.TitaniumDichloride.getItemStack(3))
                .input(dust, Magnesium)
                .output(ingotHot, Titanium)
                .output(dust, MagnesiumChloride, 3)
                .blastFurnaceTemp(2141)
                .EUt(480)
                .duration(480)
                .buildAndRegister();
        BLAST_RECIPES.recipeBuilder()
                .inputs(GTFOMaterialHandler.TitaniumIiOxide.getItemStack(4))
                .input(dust, Carbon, 3)
                .blastFurnaceTemp(2100)
                .outputs(GTFOMaterialHandler.TitaniumCarbide.getItemStack(4))
                .fluidOutputs(CarbonDioxide.getFluid(1000))
                .EUt(V[UV] * 15/16)
                .duration(4600)
                .buildAndRegister();
        RecipeUtils.chemicalDehydratorProxy().recipeBuilder()
                .inputs(GTFOMaterialHandler.TitaniumIiiOxide.getItemStack(5))
                .fluidInputs(Hydrogen.getFluid(2000))
                .outputs(GTFOMaterialHandler.TitaniumIiOxide.getItemStack(4))
                .fluidOutputs(Water.getFluid(1000))
                .EUt(V[ZPM] * 15/16)
                .duration(4000)
                .buildAndRegister();
        ARC_FURNACE_RECIPES.recipeBuilder()
                .input(dust, Titanium, 2)
                .fluidInputs(Oxygen.getFluid(3000))
                .outputs(GTFOMaterialHandler.TitaniumIiiOxide.getItemStack(5))
                .EUt(120)
                .duration(200)
                .buildAndRegister();
        LARGE_CHEMICAL_RECIPES.recipeBuilder()
                .inputs(HafniumChloride.getItemStack(15), GTFOMaterialHandler.MoscoviumTrichloride.getItemStack(8))
                .input(dust, Moscovium, 8)
                .outputs(GTFOMaterialHandler.MoscoviumHafniumOctadecachloride.getItemStack(31))
                .EUt(V[UV] * 15/16)
                .duration(448)
                .buildAndRegister();
        ARC_FURNACE_RECIPES.recipeBuilder()
                .input(dust, Hafnium)
                .fluidInputs(Oxygen.getFluid(2000))
                .outputs(HafniumOxide.getItemStack(3))
                .EUt(120)
                .duration(200)
                .buildAndRegister();
        CHEMICAL_RECIPES.recipeBuilder()
                .inputs(GTFOMaterialHandler.MoscoviumIiiOxide.getItemStack(5))
                .fluidInputs(HydrochloricAcid.getFluid(6000))
                .outputs(GTFOMaterialHandler.MoscoviumTrichloride.getItemStack(8))
                .fluidOutputs(Water.getFluid(3000))
                .EUt(7680)
                .duration(380)
                .buildAndRegister();

        CHEMICAL_PLANT_RECIPES.recipeBuilder()
                .fluidInputs(GTFOMaterialHandler.TetrabromomoscoviumTrichloroxenonComplex.getFluid(1000), Bromine.getFluid(4000))
                .notConsumable(HIGH_FREQUENCY_LASER.getStackForm())
                .outputs(GTFOMaterialHandler.MoscoviumPentabromide.getItemStack(6))
                .fluidOutputs(GTFOMaterialHandler.BromineMonochloride.getFluid(3000), Xenon.getFluid(1000))
                .EUt(V[GAValues.UIV] * 15/16)
                .duration(1440)
                .buildAndRegister();
        ELECTROLYZER_RECIPES.recipeBuilder()
                .fluidInputs(GTFOMaterialHandler.BromineMonochloride.getFluid(1000))
                .fluidOutputs(Chlorine.getFluid(1000), Bromine.getFluid(1000))
                .EUt(120)
                .duration(157)
                .buildAndRegister();
        CHEMICAL_PLANT_RECIPES.recipeBuilder()
                .inputs(PotassiumBromide.getItemStack(2))
                .fluidInputs(GTFOMaterialHandler.TribromochloromoscoviumTrichloroxenonComplex.getFluid(1000))
                .notConsumable(GTFOMaterialHandler.DimethylSulfoxide.getFluid(1))
                .output(dust, RockSalt, 2)
                .fluidOutputs(GTFOMaterialHandler.TetrabromomoscoviumTrichloroxenonComplex.getFluid(1000))
                .EUt(V[GAValues.UIV] * 15/16)
                .duration(580)
                .buildAndRegister();
        CHEMICAL_RECIPES.recipeBuilder()
                .fluidInputs(Dimethylsulfide.getFluid(1000), NitrogenDioxide.getFluid(1000))
                .fluidOutputs(GTFOMaterialHandler.DimethylSulfoxide.getFluid(1000), NitricOxide.getFluid(1000))
                .EUt(7680)
                .duration(100)
                .buildAndRegister();
        CHEMICAL_RECIPES.recipeBuilder()
                .inputs(GTFOMaterialHandler.MoscoviumTribromide.getItemStack(4))
                .fluidInputs(GTFOMaterialHandler.XenonTetrachloride.getFluid(1000))
                .fluidOutputs(GTFOMaterialHandler.TribromochloromoscoviumTrichloroxenonComplex.getFluid(1000))
                .EUt(V[UV] * 15/16)
                .duration(595)
                .buildAndRegister();
        CHEMICAL_RECIPES.recipeBuilder()
                .inputs(GTFOMaterialHandler.MoscoviumIiiOxide.getItemStack(5))
                .fluidInputs(HydrobromicAcid.getFluid(6000))
                .outputs(GTFOMaterialHandler.MoscoviumTribromide.getItemStack(8))
                .fluidOutputs(Water.getFluid(3000))
                .EUt(7680)
                .duration(373)
                .buildAndRegister();
        DECAY_CHAMBERS_RECIPES.recipeBuilder()
                .fluidInputs(GTFOMaterialHandler.IodineCxxixTrichloride.getFluid(4000))
                .fluidOutputs(GTFOMaterialHandler.XenonTetrachloride.getFluid(3000))
                .outputs(GTFOMaterialHandler.IodineCxxix.getItemStack())
                .EUt(7680)
                .duration(25000)
                .buildAndRegister();
        CHEMICAL_RECIPES.recipeBuilder()
                .inputs(GTFOMaterialHandler.IodineCxxix.getItemStack())
                .fluidInputs(Chlorine.getFluid(3000))
                .fluidOutputs(GTFOMaterialHandler.IodineCxxixTrichloride.getFluid(1000))
                .EUt(7680)
                .duration(431)
                .buildAndRegister();
        LARGE_CENTRIFUGE_RECIPES.recipeBuilder()
                .inputs(GTFOMaterialHandler.FissionedUraniumCcxxxv.getItemStack())
                .chancedOutput(OreDictUnifier.get(dust, Technetium), 613, 0)
                .chancedOutput(OreDictUnifier.get(dust, Tin), 10, 0)
                .chancedOutput(OreDictUnifier.get(dust, Zirconium), 545, 0)
                .chancedOutput(OreDictUnifier.get(dust, Caesium), 691, 0)
                .chancedOutput(OreDictUnifier.get(dust, Palladium), 124, 0)
                .chancedOutput(GTFOMaterialHandler.IodineCxxix.getItemStack(), 84, 0)
                .EUt(V[ZPM] * 3/4)
                .duration(900)
                .buildAndRegister();
        NUCLEAR_REACTOR_RECIPES.recipeBuilder()
                .input(dust, Uranium235)
                .input(dustSmall, Neutronium)
                .outputs(GTFOMaterialHandler.FissionedUraniumCcxxxv.getItemStack())
                .EUt(30720)
                .duration(700)
                .baseHeatProduction(12)
                .buildAndRegister();
        COMPRESSOR_RECIPES.recipeBuilder()
                .inputs(GTFOMaterialHandler.MoscoviumIodide.getItemStack(5))
                .outputs(GTFOMaterialHandler.MoscoviumPentaiodide.getItemStack(3))
                .EUt(V[GAValues.UMV] * 13/16)
                .duration(500)
                .buildAndRegister();
        BLAST_RECIPES.recipeBuilder()
                .inputs(GTFOMaterialHandler.MethylMoscoviumDiiodide.getItemStack(7))
                .outputs(GTFOMaterialHandler.MoscoviumIodide.getItemStack(2))
                .blastFurnaceTemp(650)
                .fluidOutputs(GTFOMaterialHandler.Iodomethane.getFluid(1000))
                .EUt(480)
                .duration(120)
                .buildAndRegister();
        CHEMICAL_RECIPES.recipeBuilder()
                .fluidInputs(GTFOMaterialHandler.Iodomethane.getFluid(2000), GTFOMaterialHandler.Trimethylmoscovide.getFluid(1000))
                .outputs(GTFOMaterialHandler.MethylMoscoviumDiiodide.getItemStack(7))
                .fluidOutputs(Propane.getFluid(1000), Methane.getFluid(1000))
                .EUt(V[UHV] * 15/16)
                .duration(260)
                .buildAndRegister();
        CHEMICAL_RECIPES.recipeBuilder()
                .inputs(GTFOMaterialHandler.MoscoviumIiiOxide.getItemStack(5), GTFOMaterialHandler.Methyllithium.getItemStack(5))
                .outputs(GTFOMaterialHandler.LithiumMoscovide.getItemStack(2))
                .fluidOutputs(GTFOMaterialHandler.Trimethylmoscovide.getFluid(1000), Oxygen.getFluid(3000))
                .EUt(7680)
                .duration(100)
                .buildAndRegister();
        ELECTROLYZER_RECIPES.recipeBuilder()
                .inputs(GTFOMaterialHandler.LithiumMoscovide.getItemStack(2))
                .outputs(OreDictUnifier.get(dust, Moscovium), OreDictUnifier.get(dust, Lithium))
                .EUt(480)
                .duration(212)
                .buildAndRegister();
        LARGE_CHEMICAL_RECIPES.recipeBuilder()
                .input(dust, Lithium, 2)
                .fluidInputs(GTFOMaterialHandler.Bromomethane.getFluid(1000))
                .notConsumable(Diethylether.getFluid(1000))
                .outputs(GTFOMaterialHandler.Methyllithium.getItemStack(5), GTFOMaterialHandler.LithiumBromide.getItemStack(2))
                .EUt(480)
                .duration(63)
                .buildAndRegister();
        ELECTROLYZER_RECIPES.recipeBuilder()
                .inputs(GTFOMaterialHandler.LithiumBromide.getItemStack(2))
                .output(dust, Lithium)
                .fluidOutputs(Bromine.getFluid(1000))
                .EUt(120)
                .duration(194)
                .buildAndRegister();
        LARGE_CHEMICAL_RECIPES.recipeBuilder()
                .input(dust, Sulfur)
                .fluidInputs(Bromine.getFluid(6000), Methanol.getFluid(6000))
                .fluidOutputs(SulfuricAcid.getFluid(1000), GTFOMaterialHandler.Bromomethane.getFluid(6000), Water.getFluid(2000))
                .EUt(7680)
                .duration(770)
                .buildAndRegister();
        CHEMICAL_RECIPES.recipeBuilder()
                .input(dust, Phosphorus)
                .input(dust, Iodine, 3)
                .fluidInputs(Methanol.getFluid(3000))
                .fluidOutputs(PhosphoricAcid.getFluid(1000), GTFOMaterialHandler.Iodomethane.getFluid(3000))
                .EUt(30720)
                .duration(559)
                .buildAndRegister();

        RecipeUtils.chemicalDehydratorProxy().recipeBuilder()
                .inputs(GTFOMaterialHandler.ShockedThalliumAstatideDust.getItemStack(4))
                .outputs(GTFOMaterialHandler.MoscoviumPentaastatide.getItemStack(3), GTFOMaterialHandler.ThalliumAstatide.getItemStack())
                .EUt(V[UV] * 15/16)
                .duration(280)
                .buildAndRegister();
        MACERATOR_RECIPES.recipeBuilder()
                .inputs(GTFOMaterialHandler.ShockedThalliumAstatideConductor.getItemStack())
                .outputs(GTFOMaterialHandler.ShockedThalliumAstatideDust.getItemStack())
                .EUt(120)
                .duration(136)
                .buildAndRegister();
        POLARIZER_RECIPES.recipeBuilder()
                .inputs(GTFOMaterialHandler.ThalliumAstatideConductor.getItemStack(3))
                .outputs(GTFOMaterialHandler.ShockedThalliumAstatideConductor.getItemStack(2))
                .EUt((V[GAValues.UXV] / 16) * 15)
                .duration(220)
                .buildAndRegister();
        VACUUM_RECIPES.recipeBuilder()
                .inputs(GTFOMaterialHandler.HeatedDopedThalliumAstatide.getItemStack())
                .outputs(GTFOMaterialHandler.ThalliumAstatideConductor.getItemStack())
                .EUt(30720)
                .duration(640)
                .buildAndRegister();
        ARC_FURNACE_RECIPES.recipeBuilder()
                .inputs(GTFOMaterialHandler.DopedThalliumAstatidePlate.getItemStack())
                .outputs(GTFOMaterialHandler.HeatedDopedThalliumAstatide.getItemStack())
                .EUt(30720)
                .duration(259)
                .buildAndRegister();
        COMPRESSOR_RECIPES.recipeBuilder()
                .inputs(GTFOMaterialHandler.DopedThalliumAstatide.getItemStack())
                .outputs(GTFOMaterialHandler.DopedThalliumAstatidePlate.getItemStack())
                .EUt(30720)
                .duration(80)
                .buildAndRegister();
        MIXER_RECIPES.recipeBuilder()
                .inputs(GTFOMaterialHandler.ThalliumAstatide.getItemStack(), GTFOMaterialHandler.MoscoviumAstatide.getItemStack())
                .outputs(GTFOMaterialHandler.DopedThalliumAstatide.getItemStack(2))
                .EUt(1920)
                .duration(85)
                .buildAndRegister();
        CHEMICAL_RECIPES.recipeBuilder()
                .inputs(GTFOMaterialHandler.ThalliumSulfate.getItemStack(7))
                .fluidInputs(GTFOMaterialHandler.HydroastaticAcid.getFluid(2000))
                .outputs(GTFOMaterialHandler.ThalliumAstatide.getItemStack(4))
                .fluidOutputs(SulfuricAcid.getFluid(1000))
                .EUt(480)
                .duration(40)
                .buildAndRegister();
        CHEMICAL_RECIPES.recipeBuilder()
                .input(dust, Thallium, 2)
                .fluidInputs(SulfuricAcid.getFluid(1000), Oxygen.getFluid(1000))
                .outputs(GTFOMaterialHandler.ThalliumSulfate.getItemStack(7))
                .fluidOutputs(Water.getFluid(1000))
                .EUt(7550)
                .duration(40)
                .buildAndRegister();
        CHEMICAL_RECIPES.recipeBuilder()
                .input(dust, Astatine, 1)
                .fluidInputs(Hydrogen.getFluid(1000))
                .fluidOutputs(GTFOMaterialHandler.HydroastaticAcid.getFluid(1000))
                .EUt(960)
                .duration(50)
                .buildAndRegister();
        CHEMICAL_RECIPES.recipeBuilder()
                .inputs(GTFOMaterialHandler.MoscoviumIOxide.getItemStack(3))
                .fluidInputs(GTFOMaterialHandler.HydroastaticAcid.getFluid(2000))
                .outputs(GTFOMaterialHandler.MoscoviumAstatide.getItemStack(2))
                .fluidOutputs(Water.getFluid(1000))
                .EUt(30720)
                .duration(140)
                .buildAndRegister();
        ARC_FURNACE_RECIPES.recipeBuilder()
                .input(dust, Moscovium, 2)
                .fluidInputs(Oxygen.getFluid(1000))
                .outputs(GTFOMaterialHandler.MoscoviumIOxide.getItemStack(3))
                .EUt(7680)
                .duration(400)
                .buildAndRegister();

        LARGE_CHEMICAL_RECIPES.recipeBuilder()
                .inputs(GTFOMaterialHandler.SupercooledMoscoviumTennesside.getItemStack(2), GTFOMaterialHandler.SupercooledTennessine.getItemStack(4))
                .fluidInputs(GTFOMaterialHandler.EntangledGluons.getFluid(1000))
                .notConsumable(HIGH_FREQUENCY_LASER.getStackForm())
                .outputs(GTFOMaterialHandler.MoscoviumPentatennesside.getItemStack(6))
                .EUt((V[GAValues.UXV] / 16) * 15)
                .duration(220)
                .buildAndRegister();
        STELLAR_FORGE_RECIPES.recipeBuilder()
                .fluidInputs(Gluons.getFluid(1000))
                .notConsumable(OreDictUnifier.get(plate, QCDMatter))
                .fluidOutputs(GTFOMaterialHandler.EntangledGluons.getFluid(1000))
                .EUt(V[UHV] * 15/16)
                .duration(43)
                .buildAndRegister();
        VACUUM_RECIPES.recipeBuilder()
                .inputs(GTFOMaterialHandler.MoscoviumTennesside.getItemStack())
                .fluidInputs(SupercooledCryotheum.getFluid(3000))
                .outputs(GTFOMaterialHandler.SupercooledMoscoviumTennesside.getItemStack())
                .EUt(V[UHV] * 15/16)
                .duration(71)
                .buildAndRegister();
        CHEMICAL_RECIPES.recipeBuilder()
                .inputs(GTFOMaterialHandler.MoscoviumIOxide.getItemStack(3), GTFOMaterialHandler.HydrotennessiticAcid.getItemStack(2))
                .outputs(GTFOMaterialHandler.MoscoviumTennesside.getItemStack(2))
                .fluidOutputs(Water.getFluid(1000))
                .EUt(V[UV] * 15/16)
                .duration(77)
                .buildAndRegister();
        CHEMICAL_RECIPES.recipeBuilder()
                .input(dust, Tennessine)
                .fluidInputs(Hydrogen.getFluid(1000))
                .EUt(V[UHV])
                .duration(200)
                .outputs(GTFOMaterialHandler.HydrotennessiticAcid.getItemStack(2))
                .buildAndRegister();
        ELECTROLYZER_RECIPES.recipeBuilder()
                .inputs(GTFOMaterialHandler.SupercooledHydrotennessiticAcid.getItemStack(2))
                .outputs(GTFOMaterialHandler.SupercooledTennessine.getItemStack())
                .fluidOutputs(LiquidHydrogen.getFluid(1000))
                .EUt(30)
                .duration(460000)
                .buildAndRegister();
        VACUUM_RECIPES.recipeBuilder()
                .inputs(GTFOMaterialHandler.HydrotennessiticAcid.getItemStack())
                .fluidInputs(SupercooledCryotheum.getFluid(3000))
                .outputs(GTFOMaterialHandler.SupercooledHydrotennessiticAcid.getItemStack())
                .EUt(V[UHV])
                .duration(68)
                .buildAndRegister();*/
    }
}
